### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by patrickheeney** [nickcharlton/boxes#2]
Great project! I wanted to compile my thoughts while using this and hopefully contribute some in the process. The goal for me is to get this working with ansible and add some more machines like centos. I am not that famaliar with ruby or rake so hopefully you can give me a bit of guidance so I can submit some pull requests.

**Default build**

When I add another provisioner "ansible" and another distro "centos", the rake -T list gets pretty long. I think `rake default` should be renamed to `rake all`. The other issue is I don't need standard, chef, puppet so I was trying to think of a better command without manually typing out each box configuration. 

Does rake have anything available to do something like `rake build --type=ansible` which would run all distros, targets, but only the type. Or you could run `rake build --distros=debian,ubuntu --type=ansible`? That way I don't have to type each configuration. 

**Adding centos**

It looks like all the common scripts are geared toward debian based systems right now. What is a good way to re-structure this to add more systems that don't share a common debian base? Should it be `common/debian/*` and `common/redhat/*`. Since debian and ubuntu share the scripts it doesn't make sense to duplicate it in each folder. 

Also I don't know that centos has codenames for builds so naming it `6.564.erb` isnt appealing. Should I rename them all to `raring-64.erb`, `centos6.5-64.erb`?

I think thats it for now.

**Comment by nickcharlton** [comment]
Closing this as it's been open a long time. I'm now working on some new (big) changes which I hope will address most, if not all of them.
