### ISSUE TITLE
Wheezy no longer on mirror.

### ISSUE THREAD

**Issue by kirjatoukka** [nickcharlton/boxes#24]
Due to wheezy being very old it no longer exists on most Debian CD mirrors. Below is a list of the mirrors that still carried it (or at least the amd64 arch) recently.

```
    http://debian.inode.at
    http://debian.carnet.hr
    http://ftp.carnet.hr
    http://debian.fastweb.it
    http://giano.com.dist.unige.it
    http://ftp.icm.edu.pl/pub/Linux
    http://debian.ethz.ch
```

**Comment by nickcharlton** [comment]
Do we need to set anything else apart from the CD mirror?

**Comment by kirjatoukka** [comment]
No, I don't think so.
